# Generated by Django 5.0.14 on 2026-03-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField()),
                ("client", models.CharField(blank=True, max_length=255)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("web-scraping", "Web Scraping & Data Extraction"),
                            ("automation", "Browser Automation"),
                            ("backend", "Backend Development"),
                            ("frontend", "Frontend Development"),
                            ("api", "API Development & Integration"),
                            ("ai", "AI Integration & Pipelines"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tech_stack",
                    models.JSONField(
                        default=list, help_text="List of technology name strings"
                    ),
                ),
                ("challenge", models.TextField(blank=True)),
                ("solution", models.TextField(blank=True)),
                ("results", models.TextField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="portfolio/"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower number appears first"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
