# Generated by Django 5.0.14 on 2026-03-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct URL to logo (e.g. SVG from CDN)",
                        max_length=500,
                    ),
                ),
                (
                    "logo_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a logo file if no URL is provided",
                        null=True,
                        upload_to="technologies/",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower number appears first"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Technologies",
                "ordering": ["order", "name"],
            },
        ),
    ]
