# Generated by Django 5.0.14 on 2026-03-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_technology_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technology",
            name="description",
        ),
    ]
