# Generated by Django 5.0.14 on 2026-03-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_remove_technology_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="technology",
            name="description",
            field=models.TextField(
                blank=True, help_text="Short description of how we use this technology"
            ),
        ),
    ]
