# Generated by Django 5.0.14 on 2026-03-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HowWeWorkSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_label",
                    models.CharField(
                        default="Our Process",
                        help_text="Small uppercase label above the title",
                        max_length=150,
                    ),
                ),
                (
                    "title_line_1",
                    models.CharField(
                        default="HOW WE",
                        help_text="First line of the main title",
                        max_length=150,
                    ),
                ),
                (
                    "title_line_2_highlight",
                    models.CharField(
                        default="WORK",
                        help_text="Second line of the title (often highlighted/colored)",
                        max_length=150,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="From requirements to production — a battle-tested process that ships fast and scales clean."
                    ),
                ),
            ],
            options={
                "verbose_name": "How We Work Settings",
                "verbose_name_plural": "How We Work Settings",
            },
        ),
        migrations.CreateModel(
            name="WorkProcessStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which this card appears (0 is first)",
                    ),
                ),
                (
                    "phase_number",
                    models.CharField(help_text="e.g. '01'", max_length=50),
                ),
                (
                    "phase_label",
                    models.CharField(
                        help_text="e.g. 'PHASE ONE' or 'Discovery'", max_length=150
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Main card title", max_length=200),
                ),
                ("description", models.TextField()),
                (
                    "tags",
                    models.JSONField(
                        default=list,
                        help_text="List of string tags (e.g. ['Requirements Audit', 'Scope Definition'])",
                    ),
                ),
                (
                    "theme_color",
                    models.CharField(
                        default="#F5C518",
                        help_text="Hex color code for this card's dynamic frosting/highlight (e.g. #F5C518)",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Process Step",
                "verbose_name_plural": "Work Process Steps",
                "ordering": ["order"],
            },
        ),
    ]
