# Generated by Django 5.0.14 on 2026-03-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("web-scraping", "Web Scraping & Data Extraction"),
                            ("automation", "Browser Automation"),
                            ("backend", "Backend Development"),
                            ("frontend", "Frontend Development"),
                            ("api", "API Development & Integration"),
                            ("ai", "AI Integration & Pipelines"),
                            ("other", "Other / Not Sure"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "budget",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under-5k", "Under $5,000"),
                            ("5k-15k", "$5,000 – $15,000"),
                            ("15k-50k", "$15,000 – $50,000"),
                            ("over-50k", "Over $50,000"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of when an admin first marked this as read",
                        null=True,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
