# Generated by Django 5.0.14 on 2026-03-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageSEO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_identifier",
                    models.SlugField(
                        help_text="Unique key for this page's SEO data. Examples: 'home', 'services', 'services-web-scraping', 'blog'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        help_text="Max 60 characters — Google truncates beyond this",
                        max_length=60,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        help_text="Max 160 characters — Google truncates beyond this",
                        max_length=160,
                    ),
                ),
                ("og_title", models.CharField(blank=True, max_length=100)),
                ("og_description", models.CharField(blank=True, max_length=200)),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Recommended size: 1200x630px",
                        null=True,
                        upload_to="seo/og/",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page URL as canonical",
                    ),
                ),
                (
                    "schema_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom JSON-LD schema override injected directly into the page",
                    ),
                ),
                ("focus_keyword", models.CharField(blank=True, max_length=100)),
                (
                    "secondary_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of secondary keyword strings",
                    ),
                ),
                (
                    "no_index",
                    models.BooleanField(
                        default=False,
                        help_text="Set True to add noindex meta — use sparingly",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Page SEO",
                "verbose_name_plural": "Page SEO Entries",
                "ordering": ["page_identifier"],
            },
        ),
    ]
