# Generated by Django 5.0.14 on 2026-03-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("role", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="team/")),
                (
                    "skills",
                    models.JSONField(
                        default=list, help_text="List of skill name strings"
                    ),
                ),
                ("github", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower number appears first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
