# Generated by Django 5.0.14 on 2026-03-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="member",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
